$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
allowCompoundWords: true
useGitignore: true
ignorePaths: []
words:
  - ianvs
  - kabanks
  - unlocalized
  - Zustand
