[tools]
node = "22.13.1"

[env]
EXPO_DEBUG = 0
EXPO_UNSTABLE_ATLAS = 1
EXPO_USE_METRO_REQUIRE = 0
# Disabled experimental tree shaking because it breaks nativewind
EXPO_UNSTABLE_METRO_OPTIMIZE_GRAPH = 0
EXPO_UNSTABLE_TREE_SHAKING = 0
